version: '3'
services:
  app:
    image: najiabderraouf/express-sqlite-app:latest
    container_name: express-sqlite-app
    ports:
      - "3000:3000"
    volumes:
      - ./mydatabase.db:/usr/src/app/mydatabase.db
#    depends_on:
#      - db
#  db:
#    image: "sqlite:latest"
#    volumes:
#      - ./mydatabase.db:/usr/src/app/mydatabase.db

